### ISSUE TITLE
Hint/error message wrong

### ISSUE THREAD

**Issue by alexander-johmann** [receptiryaki/darkside#1]
Hei, thanks a lot for the plugin!

In the hint/error message is a "s" missing in the layer style naming: "Theme**s**/…"
 
<img width="532" alt="Bildschirmfoto 2020-02-22 um 18 29 05" src="https://user-images.githubusercontent.com/2386360/75096577-468d9180-55a1-11ea-811c-f3bd528d4bc8.png">

**Comment by receptiryaki** [comment]
Thanks for your feedback 🙏I just fixed it
