### ISSUE TITLE
Do you have plan in supporting custom layer style name rules?

### ISSUE THREAD

**Issue by hzlzh** [receptiryaki/darkside#2]
like this below:
```
/skin/light/bgc
/skin/dark/bgc
/skin/red/bgc
```

**Comment by receptiryaki** [comment]
unfortunately i don't think for sketch right now. but I am preparing a more advanced plugin for figma that you can create as many themes as you wish. maybe I can apply the same features for sketch when it's done.

**Comment by hzlzh** [comment]
Cool, looking forward to your work
